name: CI Native Image Buildpacks workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the Environment to deploy'
        type: choice
        required: true
        options:
          - dev
          - qa
          - uat
          - load
          - prod
        default: 'dev'

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write # need this for OIDC
      contents: read

    environment: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.RELEASE_TOKEN }}
          cache: maven

      - name: Print debug info
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version

      - name: Build Native Image with Buildpacks
        run: |
          mvn clean -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=$DOCKER_USERNAME/${{ secrets.DOCKER_REPOSITORY_NAME }}:latest

      - name: Set project version as environment variable
        run: echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Tag and push image to Docker Hub
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ env.PROJECT_VERSION }}-native
        run: |
          echo "$DOCKER_PASSWORD" | sudo docker login -u ${DOCKER_USERNAME} --password-stdin $DOCKER_REGISTRY
          docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" 
